import moment from 'moment';

export const accountRatings = [
  { code: '01', description: 'Paid or paying as agreed', valid: true },
  { code: '02', description: '30 days past due', valid: true },
  { code: '03', description: '60 days past due', valid: false },
  { code: '04', description: '90 days past due', valid: false },
  { code: '05', description: '120 days past due', valid: false },
  { code: '07', description: 'Wage earner or similar plan', valid: false },
  { code: '08', description: 'Repossession', valid: false },
  { code: '8A', description: 'Voluntary surrender', valid: false },
  { code: '8P', description: 'Payment after repossession', valid: false },
  { code: '09', description: 'Charged off as bad debt', valid: false },
  { code: '9B', description: 'Collection account', valid: false },
  {
    code: '9P',
    description: 'Payment after charge off/collection',
    valid: false,
  },
  {
    code: 'UR',
    description:
      'Unrated or bankruptcy (remark codes will show whether the account is a bankruptcy and, if so, what type of bankruptcy)',
    valid: false,
  },
];
export const addressCodes = [
  { code: 'AD', streetType: 'Arcade' },
  { code: 'GR', streetType: 'Grove' },
  { code: 'AL', streetType: 'Alley' },
  { code: 'HL', streetType: 'Hill' },
  { code: 'AV', streetType: 'Avenue' },
  { code: 'HT', streetType: 'Heights' },
  { code: 'AX', streetType: 'Annex' },
  { code: 'HY', streetType: 'Highway' },
  { code: 'BD', streetType: 'Bend' },
  { code: 'KN', streetType: 'Knoll' },
  { code: 'BE', streetType: 'Bridge' },
  { code: 'LN', streetType: 'Lane' },
  { code: 'BF', streetType: 'Bluff' },
  { code: 'LP', streetType: 'Loop' },
  { code: 'BG', streetType: 'Burg' },
  { code: 'MA', streetType: 'Mall' },
  { code: 'BH', streetType: 'Beach' },
  { code: 'PA', streetType: 'Path' },
  { code: 'BK', streetType: 'Brook' },
  { code: 'PI', streetType: 'Pike' },
  { code: 'BL', streetType: 'Bluffs' },
  { code: 'PK', streetType: 'Park' },
  { code: 'BM', streetType: 'Bottom' },
  { code: 'PL', streetType: 'Place' },
  { code: 'BN', streetType: 'Branch' },
  { code: 'PT', streetType: 'Point' },
  { code: 'BP', streetType: 'Bypass' },
  { code: 'PY', streetType: 'Parkway' },
  { code: 'BS', streetType: 'Brooks' },
  { code: 'PZ', streetType: 'Plaza' },
  { code: 'BU', streetType: 'Burgs' },
  { code: 'RD', streetType: 'Road' },
  { code: 'BV', streetType: 'Boulevard' },
  { code: 'RN', streetType: 'Run' },
  { code: 'BY', streetType: 'Bayou' },
  { code: 'RO', streetType: 'Row' },
  { code: 'CI', streetType: 'Circle' },
  { code: 'RT', streetType: 'Route' },
  { code: 'CN', streetType: 'Center' },
  { code: 'SQ', streetType: 'Square' },
  { code: 'CR', streetType: 'Crescent' },
  { code: 'ST', streetType: 'Street' },
  { code: 'CT', streetType: 'Court' },
  { code: 'TE', streetType: 'Terrace' },
  { code: 'DA', streetType: 'Dale' },
  { code: 'TP', streetType: 'Turnpike' },
  { code: 'DR', streetType: 'Drive' },
  { code: 'TR', streetType: 'Trail' },
  { code: 'EX', streetType: 'Expressway' },
  { code: 'VI', streetType: 'Viaduct' },
  { code: 'FY', streetType: 'Freeway' },
  { code: 'WK', streetType: 'Walk' },
  { code: 'GA', streetType: 'Garden' },
  { code: 'WY', streetType: 'Way' },
];

export const provinces = [
  { code: 'AB', province: 'Alberta' },
  { code: 'BC', province: 'British Columbia' },
  { code: 'LB', province: 'Labrador' },
  { code: 'MB', province: 'Manitoba' },
  { code: 'NB', province: 'New Brunswick' },
  { code: 'NK', province: 'New Brunswick' },
  { code: 'NF', province: 'Newfoundland' },
  { code: 'NT', province: 'Northwest Territories' },
  { code: 'NW', province: 'Northwest Territories' },
  { code: 'NS', province: 'Nova Scotia' },
  { code: 'ON', province: 'Ontario' },
  { code: 'PE', province: 'Prince Edward Island' },
  { code: 'QU', province: 'Quebec' },
  { code: 'PQ', province: 'Quebec' },
  { code: 'SK', province: 'Saskatchewan' },
  { code: 'YU', province: 'Yukon' },
  { code: 'YT', province: 'Yukon' },
];

export const locations = [
  { code: 'AA', location: 'Military address in America other than Canada' },
  {
    code: 'AE',
    location: 'Military address in Europe, Middle East, or Canada',
  },
  { code: 'AP', location: 'Military address in Pacific' },
  { code: 'AS', location: 'American Samoa' },
  { code: 'CA', location: 'Canada' },
  { code: 'CZ', location: 'Canal Zone' },
  { code: 'FM', location: 'Federated States' },
  { code: 'GU', location: 'Guam' },
  { code: 'MH', location: 'Marshall Islands' },
  { code: 'MP', location: 'N. Mariana Isles' },
  { code: 'MX', location: 'Mexico' },
  { code: 'PW', location: 'Palau' },
  { code: 'PR', location: 'Puerto Rico' },
  { code: 'VI', location: 'Virgin Islands ]' },
];

export const states = [
  { code: 'AL', state: 'Alabama', numericCode: '01' },
  { code: 'AK', state: 'Alaska', numericCode: '02' },
  { code: 'AZ', state: 'Arizona', numericCode: '04' },
  { code: 'AR', state: 'Arkansas', numericCode: '05' },
  { code: 'CA', state: 'California', numericCode: '06' },
  { code: 'CO', state: 'Colorado', numericCode: '08' },
  { code: 'CT', state: 'Connecticut', numericCode: '09' },
  { code: 'DE', state: 'Delaware', numericCode: '10' },
  { code: 'DC', state: 'Washington D.C.', numericCode: '11' },
  { code: 'FL', state: 'Florida', numericCode: '12' },
  { code: 'GA', state: 'Georgia', numericCode: '13' },
  { code: 'HI', state: 'Hawaii', numericCode: '15' },
  { code: 'ID', state: 'Idaho', numericCode: '16' },
  { code: 'IL', state: 'Illinois', numericCode: '17' },
  { code: 'IN', state: 'Indiana', numericCode: '18' },
  { code: 'IA', state: 'Iowa', numericCode: '19' },
  { code: 'KS', state: 'Kansas', numericCode: '20' },
  { code: 'KY', state: 'Kentucky', numericCode: '21' },
  { code: 'LA', state: 'Louisiana', numericCode: '22' },
  { code: 'ME', state: 'Maine', numericCode: '23' },
  { code: 'MD', state: 'Maryland', numericCode: '24' },
  { code: 'MA', state: 'Massachusetts', numericCode: '25' },
  { code: 'MI', state: 'Michigan', numericCode: '26' },
  { code: 'MN', state: 'Minnesota', numericCode: '27' },
  { code: 'MS', state: 'Mississippi', numericCode: '28' },
  { code: 'MO', state: 'Missouri', numericCode: '29' },
  { code: 'MT', state: 'Montana', numericCode: '30' },
  { code: 'NE', state: 'Nebraska', numericCode: '31' },
  { code: 'NV', state: 'Nevada', numericCode: '32' },
  { code: 'NH', state: 'New Hampshire', numericCode: '33' },
  { code: 'NJ', state: 'New Jersey', numericCode: '34' },
  { code: 'NM', state: 'New Mexico', numericCode: '35' },
  { code: 'NY', state: 'New York', numericCode: '36' },
  { code: 'NC', state: 'North Carolina', numericCode: '37' },
  { code: 'ND', state: 'North Dakota', numericCode: '38' },
  { code: 'OH', state: 'Ohio', numericCode: '39' },
  { code: 'OK', state: 'Oklahoma', numericCode: '40' },
  { code: 'OR', state: 'Oregon', numericCode: '41' },
  { code: 'PA', state: 'Pennsylvania', numericCode: '42' },
  { code: 'RI', state: 'Rhode Island', numericCode: '44' },
  { code: 'SC', state: 'South Carolina', numericCode: '45' },
  { code: 'SD', state: 'South Dakota', numericCode: '46' },
  { code: 'TN', state: 'Tennessee', numericCode: '47' },
  { code: 'TX', state: 'Texas', numericCode: '48' },
  { code: 'UT', state: 'Utah', numericCode: '4' },
  { code: 'VT', state: 'Vermont', numericCode: '50' },
  { code: 'VA', state: 'Virginia', numericCode: '51' },
  { code: 'WA', state: 'Washington', numericCode: '53' },
  { code: 'WV', state: 'West Virginia', numericCode: '54' },
  { code: 'WI', state: 'Wisconsin', numericCode: '55' },
  { code: 'WY', state: 'Wyoming', numericCode: '5' },
];

export const stateOptions = states.map((s) => ({
  key: s.numericCode,
  text: s.state,
  value: s.code,
}));

export const addressTypeOptions = addressCodes.map((a) => ({
  key: a.code,
  text: `${a.code} - ${a.streetType}`,
  value: a.code,
}));

export const creditors = [
  { name: '14 / 16 Plus - COMMENITY BANK' },
  { name: '7th Avenue Retail Stores' },
  {
    name:
      'AAFES / Military Star / Army Air Force Exchange - (REQUIRES PHYSICAL SIGNATURE)',
  },
  { name: 'Abercrombie & Fitch - COMMENITY BANK' },
  { name: 'Actioncard Visa / Mc' },
  {
    name:
      'Advanta Bank Corp/Business Card &/OR CREDIT CARD, GSDM ONLY- SAME TERMS FOR BOTH',
  },
  { name: 'Amana Capital One Usa' },
  { name: 'Amazon - Synchrony Bank' },
  { name: 'American Airlines - Citi' },
  { name: 'American Appliance Capital One' },
  { name: 'American Blind - Capital One' },
  { name: 'American Eagle - Synchrony Bank' },
  { name: 'American Eagle Outfit - 16 / Synchony Bank' },
  {
    name: 'American Express-Optima/Gold Personal-No business accounts',
  },
  {
    name:
      'American General Card Services/Springleaf Financial Card Services (Must Be 19-Digit Account #)',
  },
  { name: 'American Home Furnishing - COMMENITY BANK' },
  { name: 'American Signature Furniture - COMMENITY BANK' },
  { name: 'American Tv - COMMENITY BANK' },
  { name: 'Amerimark - 7th Avenue' },
  { name: 'Ameriquest- Capital One Nevada' },
  { name: 'Ames - COMMENITY BANK' },
  { name: 'Amre Capital One Usa' },
  { name: 'Amway Capital One' },
  { name: 'Ann Taylor - COMMENITY BANK' },
  { name: 'Applied Card Bank' },
  { name: 'Arhaus Furniture - COMMENITY BANK' },
  { name: 'Art Van Capital One' },
  { name: 'Ashley Stewart - COMMENITY BANK' },
  { name: 'Ashro- 7TH AVENUE' },
  { name: 'Aspen' },
  { name: 'Aspire Visa (Majestic Visa)' },
  { name: 'Associated Brands / Dunlop Tires - Citi' },
  { name: 'Associated Liquidating - Citi' },
  { name: 'AT&T Universal - Citi' },
  { name: 'August Max - Synchrony Bank' },
  { name: 'Avenue - COMMENITY BANK' },
  { name: 'B - Moss - Citi' },
  {
    name: 'B of A Loans (Accts 749 Payoff within 5 yrs of opening....)',
  },
  { name: 'Babies R Us - Synchrony' },
  { name: 'Banana Republic - Synchrony Bank' },
  { name: 'Bancorpsouth' },
  { name: 'Bank of America - Small Business' },
  { name: 'Bank of America/AmEx (15 digits)' },
  { name: 'Bank of America/MBNA (Visa/MC/LOC)' },
  { name: 'Bank of the West (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Bankcard Services (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Barclays Bank Delaware (Case by case)' },
  { name: 'Barnett Bank- Capital One (Must be 16-digit acct. #)' },
  { name: 'BB&T (Branch Banking & Trust)' },
  { name: 'Bdp Capital One Usa' },
  { name: 'Bealls Stores - 16 - COMMENITY BANK' },
  { name: 'Bealls Stores - 9 - COMMENITY BANK' },
  { name: 'Bedford Fair Apparel' },
  { name: 'Belden Jewelers' },
  { name: 'Belks- Synchrony Bank' },
  { name: 'Beltone Capital One' },
  { name: 'Beneficial Finance/ Springleaf Financial' },
  { name: 'Bergners - COMMENITY BANK' },
  { name: 'Best Buy-Citi' },
  { name: 'Big Sur - Citi' },
  { name: 'Bill Me Later (REQUIRES PHYSICAL SIGNATURE ON AGREEMENT)' },
  { name: "Blain's Farm & Fleet Plan - Citi" },
  { name: 'Blair - COMMENITY BANK' },
  { name: 'Blaze Mastercard' },
  { name: 'Bloomingdales Premier Visa' },
  { name: 'Bloomingdales Retail/ BLOOMINGDALES MACYS' },
  { name: 'BMC Capital One Usa' },
  { name: 'BMW Bank of North America' },
  { name: 'Bombardier - Capital One' },
  { name: 'Bombardier - Sea Doo Capital One' },
  { name: 'Bombardier - Ski Doo Capital One' },
  { name: 'Bon Marche Premier Visa' },
  { name: 'Bon Ton COMMENITY BANK' },
  { name: 'Boscovs - Capital One' },
  { name: 'Bose Capital One Usa' },
  { name: 'Boston Stores COMMENITY BANK' },
  { name: 'Bowflex Capital One Usa' },
  { name: 'Bradlees Capital One Usa' },
  { name: 'Brandon Capital One - Capital One' },
  { name: "Brendle's Inc - Synchrony Bank" },
  { name: 'Breuners Capital One Usa' },
  { name: 'Bridgestone / Firestone / Meineke (Credit First National)' },
  { name: 'Brooks Brothers - Synchrony Bank' },
  { name: 'Brylane Home - COMMENITY BANK' },
  { name: 'Builders Square - Capital One' },
  { name: "Burdine's Premier Visa" },
  { name: 'C.I.T. Bank' },
  { name: 'Cabelas Club - (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Campo Tc - Synchrony Bank' },
  { name: 'Capital One - Business' },
  { name: 'Capital One / Retail Stores' },
  {
    name: 'Capital One Card Services/Capital One (Must be 16-digit acct. #/)',
  },
  { name: 'Capital One/ MC/ VISA' },
  { name: 'Capital One/Discover' },
  { name: 'Cardmember Services~Infistar~Cardmember Services' },
  { name: 'Care Credit - Synchrony Bank' },
  { name: 'Carpet One - Synchrony Bank' },
  { name: 'Carpeteria Capital One Usa' },
  { name: 'Carrier Capital One Usa' },
  { name: 'Carson Pirie Scott COMMENITY BANK' },
  { name: 'Cascade Visa' },
  { name: 'Casual Corner - Synchrony Bank' },
  { name: 'Casual Male Big & Tall - Capital One' },
  { name: 'Catherines - Spirit Of America' },
  { name: 'Cato Corporation' },
  { name: 'Chadwicks - COMMENITY BANK' },
  { name: 'Chase MC/Visa' },
  { name: 'Chevron- Synchrony Bank' },
  { name: 'Circuit City - Chase' },
  { name: 'Citgo - Citi' },
  {
    name:
      'Citi Bank Na - Retail Bank - Ready Credit / Checking Plus / Installment Loans (No 16 - Digit Accounts)',
  },
  { name: 'Citi Business' },
  { name: 'Citibank / Retail Store / Gas' },
  { name: 'Citibank American Express' },
  { name: 'Citibank Associates Bankcard (16-digit ONLY)' },
  { name: 'Citibank Banamex Usa' },
  { name: 'Citibank Travelers Bankcard (16-digit ONLY)' },
  { name: 'Citibank/ Visa/ MC (Any16 - Digit Account #)' },
  {
    name:
      'Citifinancial Retail Services/Synchrony Bank(Must Be 16 Digits, starting 6032) SEPARATE BANKS',
  },
  { name: 'Citihealth Card - Citi' },
  { name: 'Clout Visa' },
  { name: 'COMMENITY BANK /Comenity Bank/ Retail Store' },
  { name: 'Commerce Bank' },
  { name: 'Comp Usa - Capital One Usa' },
  { name: 'Compass Bank' },
  { name: 'Complete Care Inc. - Capital One' },
  { name: 'Congressional Const. Capital One' },
  { name: 'Conoco - Citi' },
  { name: 'Conoco/Synchrony' },
  {
    name:
      'Consumer Credit Grp - Citi (Ready Credit, Checking Plus, Installment Loans)',
  },
  { name: 'Cortrust Bank' },
  { name: 'Costco - Capital One' },
  { name: 'Country Door-7th Avenue' },
  { name: 'Crate And Barrel - COMMENITY BANK' },
  { name: 'Credit One' },
  { name: 'Culligan Capital One Usa' },
  { name: 'Davids Bridal - Comenity Bank' },
  { name: "Dillard's / Dillard's AmEx/ Wells Retail" },
  { name: 'Direct Charge-7th Avenue' },
  { name: 'Direct Merchants- Capital One Nevada' },
  { name: 'Discover (NO LOANS, 16 DIGITS ONLY!!)' },
  { name: 'Disney International - Synchrony Bank' },
  { name: 'Diy - Capital One' },
  { name: 'Dm Management - Citi' },
  { name: 'Dress Barn - COMMENITY BANK' },
  { name: 'Dsi Distributors - Citi' },
  { name: 'E-Trade Visa Card' },
  { name: 'Ebay Dual Card - Synchrony' },
  { name: 'Ecowater Capital One Usa' },
  { name: 'Eddie Bauer - COMMENITY BANK' },
  { name: 'Elder Beerman / Bon Ton COMMENITY BANK' },
  { name: 'Electrolux - Capital One Usa' },
  { name: 'Electrolux - Citi' },
  { name: 'Emerge Visa / Mc' },
  { name: 'Erb Lumber - COMMENITY BANK' },
  { name: 'Ethan Allen - Synchrony Bank' },
  { name: 'Express - COMMENITY BANK' },
  { name: 'Exxon - Citibank/Retail Store/ Gas' },
  { name: 'Famous Barr' },
  { name: 'Farmers State Bank' },
  { name: 'Fashion Bug- COMMENITY BANK' },
  { name: 'FIA Card Services/BofA' },
  { name: 'Fifth Third Bank' },
  { name: "Filene's" },
  { name: 'Finger Furniture - Synchrony Bank' },
  { name: 'Fingerhut Credit Advantage / Direct Marketing' },
  { name: 'Firestone / Bridgestone / Meineke (Credit First National)' },
  { name: 'First Citizens Bank' },
  { name: 'First Consumers National Bank Card / Private Label Card' },
  { name: 'First Equity Card' },
  { name: 'First Financial Bank (Visa / Mc / Fresh Start Card)' },
  { name: 'First Hawaiian Bank' },
  { name: 'First Interstate Bank' },
  { name: 'First Merit Bank' },
  { name: 'First National Bank Of Omaha' },
  { name: 'First National Credit Card' },
  { name: 'First Premier Bank Visa / Mastercard' },
  { name: 'First Savings Credit Card' },
  { name: 'First Tennessee Bank' },
  { name: 'First USA Bank - Chase' },
  { name: 'Flexplus - Synchrony Bank' },
  { name: 'Fnbo (Acquired Wells Fargo Accounts)' },
  { name: "Foley's" },
  { name: 'Footstar / Just For Feet - COMMENITY BANK' },
  { name: 'FORTIVA CREDIT CARD' },
  { name: 'Fortunoff - COMMENITY BANK' },
  { name: 'Fred Meyer - Citi' },
  { name: 'Fred Meyer Jewelers - Synchrony Bank' },
  { name: 'Freedom Card - Emerge' },
  { name: 'Friedlanders' },
  { name: "Friedman's Jewelers - COMMENITY BANK" },
  { name: 'Frys Electronics' },
  { name: 'Fun Charge-7th Avenue' },
  { name: 'Furniture Row / Capital One' },
  { name: 'Future Shop - Citi' },
  { name: 'Gap - Synchrony Bank' },
  { name: 'Garden Ridge - COMMENITY BANK' },
  { name: 'Gateway - Citi' },
  { name: 'Gateway Capital One Usa' },
  { name: 'Ge Cap Abd (2) - Synchrony Bank' },
  { name: 'Ge Cap National (3) - Synchrony Bank' },
  { name: 'Gecap Business 4 Business - Synchrony Bank' },
  { name: 'Gecap National (4) - Synchrony Bank' },
  { name: 'Geico Platinum Mastercard' },
  { name: 'Gemaire - Capital One Usa' },
  { name: "Ginny's-7th Avenue" },
  { name: 'GM Card - Capital One (Must be 16-digit acct. #)' },
  { name: "Goldsmith's Premier Visa" },
  { name: 'Good Guys - Capital One' },
  { name: 'Goodman Jewelers' },
  { name: 'Goodyear - Citi' },
  { name: 'Goodys - COMMENITY BANK' },
  { name: 'Gordmans - COMMENITY BANK' },
  { name: 'Gordons - Citi' },
  { name: 'Gottschalks Capital One Usa' },
  { name: 'Grossmans - COMMENITY BANK' },
  { name: 'Guitar Center - Synchony Bank' },
  { name: 'Haband - COMMENITY BANK' },
  { name: 'Hague Water - Capital One Usa' },
  { name: 'Hanks Furniture - Capital One' },
  { name: 'Harlem Furniture - COMMENITY BANK' },
  { name: 'HC Processing Center (REQUIRE PHYSICAL SIGNATURE)' },
  { name: 'Healthcare Creditline Den - Capital One' },
  { name: 'Hearing Health Care - Capital One' },
  { name: 'Hechingers - Synchrony Bank' },
  { name: "Hecht's" },
  { name: 'Helpcard - (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Helzberg Diamond - Capital One Usa' },
  { name: 'Helzberg Diamonds - Citi' },
  { name: 'Henri Bendel - COMMENITY BANK' },
  { name: 'Herbergers - COMMENITY BANK' },
  {
    name:
      'Hfc / Bfc / SpringLeaf Financial. (Accounts can be 8, 11 or 12 digits.)',
  },
  { name: 'HH Greg - Synchrony' },
  { name: 'Hidden Oak Group' },
  { name: 'Hifi.com - Citi' },
  { name: 'Home Depot - Citi' },
  { name: 'Home Designs - Synchrony Bank' },
  { name: 'Home Quarters Warehouse - Synchrony Bank' },
  { name: 'Home Shopping Network - COMMENITY BANK' },
  { name: 'Homebase Capital One Usa - Cccs' },
  { name: 'Homemakers Capital One Usa' },
  { name: 'Hp Shopping.com Capital One' },
  { name: 'Huntington National Bank' },
  { name: 'Ikea Capital One' },
  { name: 'Imagine- Synchrony Bank' },
  { name: 'Infistar Cardholder Services' },
  { name: 'Intercity Capital One' },
  { name: 'Intrust Bank' },
  { name: 'Ionics - Capital One Usa' },
  { name: 'J Crew - COMMENITY BANK' },
  { name: 'J.JILL' },
  { name: 'Jared Jewelers' },
  { name: 'JB Robinson Jewelers' },
  { name: 'Jc Penney - Synchrony Bank' },
  { name: 'Jc Penney Dual - Synchrony Bank' },
  { name: 'Jck / Brendans / Bullocks And Losee - Citi' },
  { name: 'Jessica London - COMMENITY BANK' },
  { name: 'Jewelry Three - Citi' },
  { name: 'John Deere Credit (Case by case scenario)' },
  { name: 'Jones Store' },
  { name: 'Jordans Capital One Usa' },
  { name: 'Jos A Bank Clothiers - Synchrony Bank' },
  { name: 'Juniper Bank (Case by case)' },
  { name: 'Kane Furniture - COMMENITY BANK' },
  { name: "Kaufmann's" },
  { name: 'Kawasaki - Capital One Usa' },
  { name: 'Kay Jewelers - Sterling Jewelers' },
  { name: 'Kelly Tires - Citi' },
  { name: 'Kidsource - Synchrony Bank' },
  { name: 'King Size - COMMENITY BANK' },
  { name: 'Kittles Furniture - Capital One' },
  { name: 'Kmart Capital One Usa' },
  { name: 'Kohls' },
  { name: 'Kroger Card Services' },
  { name: 'L.s. Ayres' },
  { name: 'La Curacao' },
  { name: 'La Redoute - COMMENITY BANK' },
  { name: 'Lane Bryant - Spirit of America' },
  { name: 'Lazarus Premier Visa' },
  { name: 'Lennox Capital One Usa' },
  { name: 'Lerner - COMMENITY BANK' },
  { name: 'Leroy Jewelers - Sterling Jewelers' },
  { name: 'Les Schwab Tires' },
  { name: 'Levin Furniture - COMMENITY BANK' },
  { name: 'Levitz Furniture - Capital One Usa' },
  { name: 'Limited Too - COMMENITY BANK' },
  { name: 'Linens And Things - Synchrony Bank' },
  { name: 'Litman & Clay - Citi' },
  { name: 'LL Bean - Barclays Bank Delaware' },
  { name: 'Lord & Taylor- Synchrony Bank' },
  { name: "Lowe's - Synchrony Bank (No Project Cards)" },
  { name: "Macy's - All Divisions (10-13 Digit account #'s)" },
  { name: "Macy's A&S" },
  { name: "Macy's Platinum Star Rewards" },
  { name: "Macy's Premier Visa" },
  { name: "Macy's Visa" },
  { name: 'Macys - American Express' },
  { name: 'Magnolia Audio Video - Capital One' },
  { name: 'Mariannes - COMMENITY BANK' },
  { name: 'Marks and Morgan Jewelers' },
  { name: 'Marlo Furniture - Capital One Usa' },
  { name: "Marshall Field's" },
  { name: 'Mason Direct' },
  { name: "Massey's Credit - 7th Avenue" },
  { name: 'Mastercraft - COMMENITY BANK' },
  { name: 'Maurices - COMMENITY BANK' },
  { name: 'Mbia Mc / Visa' },
  { name: 'Meier & Frank' },
  { name: 'Meijer - Synchrony Bank' },
  { name: "Men's Warehouse - Synchrony Bank" },
  { name: 'Menards Capital One Usa' },
  { name: 'Mercury First Bank and Trust' },
  { name: 'Merksamer Jewelers - Synchrony Bank' },
  { name: 'Merrick Bank Visa / Mc' },
  { name: "Mervyn/'s" },
  { name: 'Metrostyle - COMMENITY BANK' },
  { name: 'Microcenter - COMMENITY BANK' },
  { name: 'Midnight Velvet-7th Avenue' },
  { name: 'Mitsubishi Electronics - Capital One Usa' },
  { name: 'Mobil Oil - Synchrony Bank' },
  { name: 'Modern Woman - Capital One Usa' },
  { name: 'Mohawk Industries - Synchrony Bank' },
  { name: 'Monroe & Main-7th Avenue' },
  { name: 'Montgomery Wards/ 7TH AVENUE -' },
  { name: 'Mvp Capital One' },
  {
    name: 'National City Visa / Mc (aka PNC Bank)(REQUIRES PHYSICAL SIGNATURE)',
  },
  { name: 'National Tire & Battery - Citi' },
  { name: 'NATIONWIDE CREDIT UNION' },
  { name: 'Nautilus Capital One' },
  { name: 'Navy Federal Credit Union - Credit Card' },
  { name: 'Navy Federal Credit Union - Loans' },
  { name: 'Neiman Marcus- Capital One' },
  { name: 'New York & Co - COMMENITY BANK' },
  {
    name:
      'Newegg.com Preferred Account (REQUIRES PHYSICAL SIGNATURE ON AGREEMENT)',
  },
  { name: 'Newport News- COMMENITY BANK' },
  { name: 'Nextcard Credit Card (Now Merrick)' },
  { name: 'Nordictrack - Synchrony Bank' },
  { name: "Nordstrom's Retail / Visa" },
  { name: 'Office Depot - Commercial' },
  { name: 'Office Depot - Personal' },
  { name: 'Office Max - Capital One' },
  { name: 'Old Navy - Synchrony Bank' },
  { name: 'OneStopPlus.com - COMMENITY BANK' },
  { name: 'Option Visa' },
  { name: 'Orchard Bank- Capital One (Must be 16-digit acct.)' },
  { name: 'Oreck - Capital One' },
  { name: 'Osh' },
  { name: 'Osterman Jewelers - Sterling Jewelers' },
  { name: 'Pacific Sunwear - COMMENITY BANK' },
  { name: 'Palais Royal - COMMENITY BANK' },
  { name: 'Parisian COMMENITY BANK' },
  { name: 'Parkwest Galleries - Capital One' },
  { name: 'Partners First' },
  { name: 'Paul Harris - Citi' },
  { name: 'Payless Capital One Usa' },
  { name: 'PayPal- Synchrony Bank' },
  { name: 'Peach Direct Capital One' },
  { name: 'Peebles - COMMENITY BANK' },
  { name: 'Peoples Bank - Rbs Visa/Mc' },
  { name: 'Petite Sophisticate - Synchrony Bank' },
  { name: 'Phillips 66 / Synchrony (Accts starting 707622...)' },
  { name: 'Phillips 76 - Citi' },
  { name: 'Pier 1 - COMMENITY BANK' },
  { name: 'Plains Commerce Bank' },
  { name: 'PNC Bank (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Polaris - Capital One Usa' },
  { name: 'Polo Ralph Lauren - COMMENITY BANK' },
  { name: 'Pottery Barn - COMMENITY BANK' },
  { name: 'Presidio Mc / Visa' },
  { name: 'QVC- Synchrony Bank' },
  { name: 'Radio Shack - Citi' },
  { name: 'RBC' },
  { name: 'Rbs Visa / Mastercard - (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Reeds Jewelers - COMMENITY BANK' },
  { name: 'Reflect Visa' },
  { name: 'Restoration Hardware - COMMENITY BANK' },
  { name: 'Resurgent Capital Services / Lvnv Funding Llc' },
  { name: 'Rev Charger - Capital One Usa' },
  { name: 'Rewards of Sports - Synchrony Bank' },
  { name: 'Rhodes Furniture - Capital One' },
  { name: "Rich's Macy's" },
  { name: "Rich's Premier Visa" },
  { name: 'Riddles Jewelry - Citi' },
  { name: 'Roamans - COMMENITY BANK' },
  { name: 'Robins Brothers' },
  { name: "Robinson's May" },
  { name: 'Rogers Jewelers - Citi' },
  { name: 'Rolox Capital One - Usa' },
  { name: 'Rooms To Go - Capital One Usa' },
  { name: 'Rooms To Go - Synchrony Bank' },
  { name: 'Roomstore Capital One Usa' },
  { name: 'Rotmans - Capital One' },
  { name: 'Saks Fifth Avenue / Saks/CAPITAL ONE' },
  { name: 'Salute' },
  { name: 'Sam Ash Music - Capital One' },
  { name: 'Sams Club - Synchrony Bank' },
  { name: 'Sams Club / Discover' },
  { name: 'Samuels - COMMENITY BANK' },
  { name: 'Savon Furniture - COMMENITY BANK' },
  { name: "Schuster's Inc Capital One" },
  { name: "Scotty's Inc - Synchrony Bank" },
  { name: "Seaman's Furniture Capital One Usa" },
  { name: 'Sears Capital One' },
  { name: 'Sears Citi' },
  { name: 'Security Bankcard Center' },
  { name: 'Security Finance' },
  { name: 'Select Visa' },
  { name: 'Service Merchandise - Capital One Usa' },
  { name: 'Service Merchandise - COMMENITY BANK' },
  { name: 'Seventh Avenue- 7th Avenue' },
  { name: 'Shaw Carpet - Synchrony Bank' },
  { name: 'Shaw Jewelers' },
  { name: 'Shell - Citi ONLY 9 or 10 DIGITS' },
  { name: 'Shop Nbc - COMMENITY BANK' },
  { name: 'Shopsmith Capital One Usa' },
  { name: 'Simplicity Manufacturing - Synchrony Bank' },
  { name: 'Sizes - COMMENITY BANK' },
  { name: 'Sizes Unlimited - COMMENITY BANK' },
  { name: "Smith's Home Furnishings - Synchrony Bank" },
  { name: 'Snapper - Synchrony Bank' },
  { name: 'Sony Financial Capital One' },
  { name: 'Sound Advice Capital One' },
  { name: 'Spiegel - COMMENITY BANK' },
  { name: 'Spirit of America Retail Stores' },
  { name: 'Sports Authority - COMMENITY BANK' },
  {
    name: 'SpringLeaf Financial / One Main (Accounts will be 12 digits.)',
  },
  { name: 'SST-Columbia Bank & Trust (formally Providian/WaMu)' },
  { name: 'Stage Stores - COMMENITY BANK' },
  { name: 'Staples Commericial' },
  { name: 'Staples Personal - Dmp' },
  { name: 'State Farm Credit Card' },
  { name: 'Stein Mart - Synchrony' },
  { name: 'Steinbach - COMMENITY BANK' },
  { name: 'Sterling Jewelers' },
  { name: "Strawbridge's" },
  { name: 'Structure - COMMENITY BANK' },
  { name: 'Sue Brett - COMMENITY BANK' },
  { name: 'Sunbelt' },
  { name: 'Sunoco - Citi' },
  {
    name: 'Suntrust (Accts starting 4425..) -(REQUIRES PHYSICAL SIGNATURE)',
  },
  { name: 'Superstores Of America - Capital One' },
  { name: 'Suzuki Capital One Usa' },
  { name: 'Swiss Colony-7th Avenue' },
  { name: 'Synchrony / Retail Store' },
  { name: 'Synchrony Bank/Citifinancial Retail' },
  { name: "Synchrony Consumer Card (13 Or 16 - Digit Account #'s)" },
  { name: 'Synchrony/American Express' },
  { name: 'Target Retail Account is 9 Digits ONLY' },
  { name: 'Target Visa (Must Be 16 - Digit Account #)' },
  { name: 'TD Bank N.A. (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Texaco - Citi' },
  { name: 'The Bedroom Superstore Capital One Usa' },
  { name: 'The Buckle - COMMENITY BANK' },
  { name: 'The Childrens Place - Citi' },
  { name: 'The Limited - COMMENITY BANK' },
  { name: 'The Sportsmans Guide Visa - COMMENITY BANK' },
  { name: 'TJ Maxx / Synchrony' },
  { name: 'Todays Man - COMMENITY BANK' },
  { name: 'Town North Bank' },
  { name: 'Toys R Us - Synchrony' },
  { name: 'Tractor Supply - Citi' },
  { name: 'Tribute - Cardholder Services' },
  { name: 'Union 76 - Citi' },
  { name: 'Union 76/Synchrony' },
  { name: 'Union Plus - Capital One (Must be 16-digit acct.)' },
  { name: 'United Consumers Club - COMMENITY BANK' },
  { name: 'United Missouri Bank - (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'US Bank (16 - Digit Account #)' },
  { name: 'US Bank Business (16-digit Account #)' },
  { name: 'USAA FSB - Loans (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Usaa Usb Visa / Mc - (REQUIRES PHYSICAL SIGNATURE)' },
  { name: 'Valero' },
  { name: 'Value City Dept Store Capital One' },
  { name: 'Value City Furniture - COMMENITY BANK' },
  { name: 'Victoria Secret - COMMENITY BANK' },
  { name: 'Wachovia/ MC & Visa' },
  { name: 'Walmart - Capital One' },
  { name: 'Walmart Discover Dual - Capital One' },
  { name: 'Walter E Smith Furniture Capital One' },
  { name: "Weberg's Capital One Usa" },
  { name: 'Weisfield Jewelers - Sterling Jewelers' },
  { name: "Wells Fargo Bank (16-digit Account #/'s starting 4465)" },
  { name: 'Wells Fargo Financial (10 Digits)' },
  { name: 'Wells Fargo Financial (16-digit Account #)' },
  { name: 'Wells Fargo Financial (8 Digit Accounts)' },
  { name: 'Wells Fargo Financial Retail (16 Digit accounts)' },
  { name: 'Wells Fargo Personal LOC (REQUIRES PHYSICAL SIGNATURE)' },
  { name: "Wells Fargo/Wachovia (16 Digit acct#/'s)" },
  { name: 'Wells/Wachovia PLC (10 digits)' },
  { name: 'Wescom Credit Union' },
  { name: 'West Building - COMMENITY BANK' },
  { name: 'Westport - COMMENITY BANK' },
  { name: 'Wickes Lumber - COMMENITY BANK' },
  { name: 'Winbook - COMMENITY BANK' },
  { name: 'Woman Within - COMMENITY BANK' },
  { name: 'Woodcraft - COMMENITY BANK' },
  { name: 'Yamaha Capital One Usa' },
  { name: 'Yamaha Music Capital One Usa' },
  { name: 'Yard Card' },
  { name: 'York - Capital One' },
  { name: 'Younkers COMMENITY BANK' },
  { name: 'Zales - Citi' },
  { name: 'Zions Bank' },
];

export const creditorOptions = creditors.map((c, index) => ({
  key: index,
  text: c.name,
  value: index,
}));

const hardshipReasons = [
  { name: 'Select Hardship Reason' },

  { name: 'Poor Money Management' },
  { name: 'Reduced Income/Unemployment' },

  { name: 'Personal Conflict (Divorce or Separated)' },

  { name: 'Medical Expense, Accident or Disability' },

  { name: 'Death of Family Member' },
  { name: 'Confidential Matter' },
  { name: 'Not Classified/Other' },
];

export const hardshipReasonsOptions = hardshipReasons.map((h, index) => ({
  key: index,
  text: h.name,
  value: index,
}));

const martialStatus = [
  { value: 'S', name: 'Single' },
  { value: 'M', name: 'Married' },
  { value: 'D', name: 'Divorced/Separated' },
];

export const martialStatusOptions = martialStatus.map((m, index) => ({
  key: index,
  text: m.name,
  value: m.value,
}));

export const monthOptions = () => {
  const empty = [{ key: 0, text: '', value: '' }];

  const allMonths = moment.months().map((m, index) => ({
    key: index + 1,
    text: m,
    value: index + 1,
  }));

  return [...empty, ...allMonths];
};

export const dayOptions = (month: number, year: number, ordinal?: boolean) => {
  const empty = [{ key: -1, text: '', value: '' }];
  const monthYear = moment(`${year}-${month + 1}`, 'YYYY-MM');
  const daysInMonth = monthYear.daysInMonth();
  const daysArray = Array.from(new Array(daysInMonth)).map((d, index) => {
    return {
      key: index + 1,
      text: ordinal ? moment.localeData().ordinal(index + 1) : index + 1,
      value: index + 1,
    };
  });

  return [...empty, ...daysArray];
};

export const yearOptions = (startYear?: number, endYear?: number) => {
  const currentYear = new Date().getFullYear(),
    years = [{ key: -1, text: '', value: '' }];
  startYear = startYear || 1910;

  const endLoopYear = !endYear ? currentYear : endYear;

  for (let i = endLoopYear; i > startYear; i--) {
    years.push({ key: i, text: i.toString(), value: i.toString() });
  }
  return years;
};

const bankAccountType = [
  { value: 'checking', name: 'Checking Account' },
  { value: 'savings', name: 'Savings Account' },
];

export const bankAccountTypeOptions = bankAccountType.map((t, index) => ({
  key: index,
  text: t.name,
  value: t.value,
}));

export const dayToMakePaymentOptions = (isSecondDay?: boolean) => {
  return [
    ...(isSecondDay
      ? [{ key: 0, text: 'I only want to pay one time a month', value: 0 }]
      : []),
    ...dayOptions(0, 2010, true),
  ].sort((a, b) => a.key - b.key);
};
